// Action Types goes here

export const BASE_URL = "http://localhost:8000"
export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES"
export const UPDATE_FLAT_CATEGORIES = "UPDATE_FLAT_CATEGORIES"
export const UPDATE_STATUS = "UPDATE_STATUS"
export const UPDATE_USER = "UPDATE_USER"
export const UPDATE_PROVINCES = "UPDATE_PROVINCES"
export const UPDATE_BANKS = "UPDATE_BANKS"
export const UPDATE_LOADING_USER = "UPDATE_LOADING_USER"
export const UPDATE_CONFIGS = "UPDATE_CONFIGS"
export const UPDATE_BASKET = "UPDATE_BASKET"
export const LOADING_BASKET = "LOADING_BASKET"

