import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className='d-flex align-items-center justify-content-center' style={{height:" 500px"}}>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <h1 className={styles.title + " text-center " }>
          Welcome to <a>Khaatoon !</a>
        </h1>
      


    </div>
  )
}
